# Generated by Django 5.2.9 on 2026-01-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="discount_percent",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
